{% set version = "2.0.5" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-groupdata2
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/groupdata2_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/groupdata2/groupdata2_{{ version }}.tar.gz
  sha256: 3f32900c0a32f5a274700012cd25e1f2d2f7ccdac8fd0f3f015f1403d1b5087f

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-checkmate >=2.0.0
    - r-dplyr >=0.8.4
    - r-lifecycle
    - r-numbers >=0.7_5
    - r-plyr >=1.8.5
    - r-purrr
    - r-rearrr >=0.3.0
    - r-rlang >=0.4.4
    - r-tibble >=2.1.3
    - r-tidyr
  run:
    - r-base
    - r-checkmate >=2.0.0
    - r-dplyr >=0.8.4
    - r-lifecycle
    - r-numbers >=0.7_5
    - r-plyr >=1.8.5
    - r-purrr
    - r-rearrr >=0.3.0
    - r-rlang >=0.4.4
    - r-tibble >=2.1.3
    - r-tidyr

test:
  commands:
    - $R -e "library('groupdata2')"           # [not win]
    - "\"%R%\" -e \"library('groupdata2')\""  # [win]

about:
  home: https://github.com/ludvigolsen/groupdata2
  license: MIT
  summary: Methods for dividing data into groups. Create balanced partitions and cross-validation folds. Perform time series windowing and general grouping and splitting of data. Balance existing groups with up- and downsampling or collapse them to fewer groups.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
